name: projectappsos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  firebase_core: ^3.12.1    # อัปเดตจาก 2.32.0
  firebase_auth: ^5.5.1     # อัปเดตจาก 4.16.0
  cloud_firestore: ^5.6.5   # อัปเดตจาก 4.17.5
  geolocator: ^13.0.2       # อัปเดตจาก 10.1.1
  url_launcher: ^6.2.4      # ไม่มีในรายการ outdated ยังใช้ได้
  shared_preferences: ^2.2.2 # ไม่มีในรายการ outdated ยังใช้ได้
  permission_handler: ^11.3.1
  sensors_plus: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0     # อัปเดตจาก 4.0.0

flutter:
  uses-material-design: true